title: tsondt
url: https://tsondt.com
baseurl:
author:
  name: tsondt
  url: https://tsondt.com

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - "src"
  - "*.sh"
  - "Dockerfile"
  - "Gemfile*"
  - "LICENSE"
  - "README.md"
  - "CNAME"

gems:
  - jekyll-sitemap

my_name: tsondt
my_title: InfoSec Addict
my_avatar: "https://avatars1.githubusercontent.com/u/3180442"

ga_id: UA-103691933-1

github_url: https://github.com/tsondt
linkedin_url: https://linkedin.com/in/tsondt
twitter_url: https://twitter.com/tsondt
blog_url: https://blog.tsondt.com
wiki_url: https://wiki.tsondt.com
oscp_url: https://oscp.tsondt.com
osce_url: https://osce.tsondt.com
photos_url: https://photos.tsondt.com

cv:
  title: Tran Thai Son Dinh
  url: https://tsondt.com/cv
